#!/usr/bin/env python3
"""Create and verify this host's agent-config symlink farm.

Every agent insists on finding rules, skills and subagents at its own path,
under its own filename. The content is authored once in `~/.agent-rules/` and
each agent's directory gets a symlink into it, so there are no copies to drift
apart.

    python3 install.py            # create anything missing
    python3 install.py --check    # report only, exit 1 if anything is missing

Deliberately conservative about which agents it touches:

  * A link is only created if its *parent agent directory already exists*
    (except `~/.gemini/config/`, which this script may create because
    Antigravity is installed and that is where it looks for global skills).
  * Codex links use `$CODEX_HOME` when set. The user skills path remains
    `~/.agents/skills`, which the installer creates once Codex exists.
  * A real file (not a symlink) sitting where a link belongs is reported as a
    conflict and left alone.

Codex's `$CODEX_HOME/AGENTS.md` is written at install time: `AGENTS.md`,
`host.md` and `harness/codex/codex.md` concatenated in that order, with in-tree
`` `../ `` pointers made absolute. A user-owned file at that path is left
alone.

Shared subagents reach Codex as generated `$CODEX_HOME/agents/<n>.toml`
files, Cursor as generated `~/.cursor/agents/<n>.md` files, and Antigravity as
generated `~/.gemini/config/agents/<n>.md` files (written, not linked: each
wants model inline, and Antigravity requires `subagent: true`), with the rungs
read from `effort-models.json`.

Cursor's `~/.cursor/hooks.json` is generated from the same lifecycle job
list as Codex (Codex event names mapped onto Cursor event names), plus
Cursor-only family-gate and subagentStop jobs. Unknown user hooks are
preserved. The tracked `.cursor/hooks.json` in this repo is checked
against that renderer.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import tempfile
from pathlib import Path

HOST = Path(__file__).resolve().parent.parent
HOME = Path.home()
CODEX_HOME = Path(os.environ.get("CODEX_HOME", HOME / ".codex")).expanduser()

SKILLS = HOST / "skills"
AGENTS = HOST / "agents"
HOST_RULES = HOST / "AGENTS.md"
# Order matches the former sync_host_rules.codex_plan(): portable rules,
# then the lab overlay, then Codex harness mechanics.
CODEX_HOST_RULE_SOURCES = ("AGENTS.md", "host.md", "harness/codex/codex.md")
CODEX_HOST_RULES_BANNER = (
    "<!-- generated by .agent-rules/scripts/install.py — edit AGENTS.md "
    "(+ host.md, harness/codex/codex.md) -->"
)
EFFORT_MODELS = HOST / "harness" / "effort-models.json"
CODEX_HOME_SET = "CODEX_HOME" in os.environ


# ---------------------------------------------------------------------------
# Agent Plugins v1 portable core
# ---------------------------------------------------------------------------


def _frontmatter(path: Path) -> dict[str, str]:
    """Minimal YAML-ish frontmatter: `key: value` lines between --- fences."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end < 0:
        return {}
    block = text[3:end].strip()
    out: dict[str, str] = {}
    for line in block.splitlines():
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        out[key.strip()] = val.strip().strip("\"'")
    return out


def validate_plugin() -> list[tuple[str, str]]:
    """Agent Plugins core is not required; catalogs may be absent."""
    return []


def _ap_server_to_catalog(spec: dict) -> dict:
    """Map Agent Plugins mcpServers entry → host upsert shape."""
    stype = spec.get("type")
    if stype == "stdio":
        entry: dict = {"command": spec["command"]}
        if "args" in spec:
            entry["args"] = spec["args"]
        if "env" in spec:
            entry["env"] = spec["env"]
        return entry
    if stype in {"streamable-http", "sse"}:
        entry = {"url": spec["url"]}
        if "headers" in spec:
            entry["headers"] = spec["headers"]
        return entry
    raise ValueError(f"unsupported MCP server type: {stype!r}")


def load_catalog() -> dict[str, dict]:
    """Shared MCP catalog is unused; keep a stable empty return."""
    return {}


# ---------------------------------------------------------------------------
# Symlink farm
# ---------------------------------------------------------------------------


class Link:
    def __init__(
        self,
        link: Path,
        target: Path,
        why: str,
        requires: Path | None = None,
        create_parents: bool = False,
    ) -> None:
        self.link = link
        self.target = target
        self.why = why
        # Directory that must already exist for this link to be wanted at all.
        self.requires = requires
        # Directories this script may create on the way (only ever inside an
        # agent directory that already exists, or ~/.gemini/config/).
        self.create_parents = create_parents

    @property
    def wanted(self) -> bool:
        return self.requires is None or self.requires.is_dir()

    def status(self) -> str:
        if not self.wanted:
            return "skipped"
        if self.link.is_symlink():
            return "ok" if self.link.resolve() == self.target.resolve() else "wrong"
        if self.link.exists():
            return "conflict"
        return "missing"


def plan() -> list[Link]:
    links: list[Link] = []

    # --- host-wide prose -------------------------------------------------
    links.append(
        Link(
            HOME / "AGENTS.md",
            HOST_RULES,
            "Cursor, for a session opened on the home directory",
        )
    )
    links.append(
        Link(
            HOME / ".gemini" / "AGENTS.md",
            HOST_RULES,
            "Antigravity native global AGENTS.md (v1.20.3+)",
            requires=HOME / ".gemini",
        )
    )
    # Codex $CODEX_HOME/AGENTS.md is written by apply_codex_agents(), not linked.

    links.append(
        Link(
            CODEX_HOME / "hooks.json",
            HOST / "harness" / "codex" / "codex-hooks.json",
            "Codex lifecycle hooks",
            requires=CODEX_HOME,
        )
    )
    links.append(
        Link(
            HOME / "bin" / "git-clean-merged-worktrees",
            HOST / "scripts" / "clean-merged-worktrees.py",
            "cross-project git worktree cleanup CLI on PATH",
            requires=HOME / "bin",
        )
    )
    # --- skills ----------------------------------------------------------
    if SKILLS.is_dir():
        for skill in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
            links.append(
                Link(
                    HOME / ".claude" / "skills" / skill.name,
                    skill,
                    "Claude Code (and Cursor, which also reads this path)",
                    requires=HOME / ".claude",
                    create_parents=True,
                )
            )
            links.append(
                Link(
                    HOME / ".gemini" / "config" / "skills" / skill.name,
                    skill,
                    "Antigravity global skills",
                    requires=HOME / ".gemini",
                    create_parents=True,
                )
            )
            links.append(
                Link(
                    HOME / ".copilot" / "skills" / skill.name,
                    skill,
                    "Copilot CLI personal skills",
                    requires=HOME / ".copilot",
                    create_parents=True,
                )
            )
            links.append(
                Link(
                    HOME / ".agents" / "skills" / skill.name,
                    skill,
                    "cross-tool global skills (Codex, Cursor, Copilot)",
                    requires=CODEX_HOME if CODEX_HOME.is_dir() else HOME / ".agents",
                    create_parents=True,
                )
            )

    # --- subagents -------------------------------------------------------
    if AGENTS.is_dir():
        for agent in sorted(AGENTS.glob("*.agent.md")):
            stem = agent.name.removesuffix(".agent.md")
            links.append(
                Link(
                    HOME / ".claude" / "agents" / f"{stem}.md",
                    agent,
                    "Claude Code (and Cursor, as a compatibility path)",
                    requires=HOME / ".claude",
                    create_parents=True,
                )
            )
            # Cursor and Antigravity native agents are generated files, not source symlinks.
            # `model: opus` on the shared markdown is applied at spawn time and
            # denied by family gates (and Antigravity requires `subagent: true`).
            # See apply_cursor_agents() and apply_antigravity_agents().
            links.append(
                Link(
                    HOME / ".copilot" / "agents" / agent.name,
                    agent,
                    "Copilot CLI personal agents",
                    requires=HOME / ".copilot",
                    create_parents=True,
                )
            )

    return links


def relative_target(link: Path, target: Path) -> str:
    try:
        return os.path.relpath(target, link.parent)
    except ValueError:
        return str(target)


def apply(item: Link) -> bool:
    """Create a missing link, or retarget a HOST-owned link after a layout move.

    A real file, or a symlink pointing outside HOST, is left alone.
    """
    if item.link.is_symlink():
        try:
            current = item.link.resolve()
            desired = item.target.resolve()
        except OSError:
            return False
        if current == desired:
            return True
        try:
            current.relative_to(HOST)
            desired.relative_to(HOST)
        except ValueError:
            return False
        item.link.unlink()
        item.link.symlink_to(relative_target(item.link, item.target))
        return True
    if item.link.exists():
        return False
    if item.create_parents:
        item.link.parent.mkdir(parents=True, exist_ok=True)
    item.link.symlink_to(relative_target(item.link, item.target))
    return True


# ---------------------------------------------------------------------------
# Shared subagents → generated Codex agent TOML
# ---------------------------------------------------------------------------
#
# Codex has no agent-file format that can be symlinked: it wants a TOML file
# per agent under `$CODEX_HOME/agents/`, carrying the model and reasoning
# effort inline. So these are *written*, not linked, and `--check` compares
# the rendered text with what is on disk. The rungs come from
# `effort-models.json` so this host has one map, not two.

# Every shared agent is a junior rung except the escalation one.
CODEX_ESCALATION_AGENTS = {"stuck-escalation"}
CODEX_OWNER_MARKER = "# coding-agent-config installer ownership: codex-v1"
CODEX_DIGEST_PREFIX = "# coding-agent-config installer digest: sha256:"

# Codex's native role schema is deliberately narrower than the shared Claude
# agent frontmatter.  Keep this contract next to the renderer so a source
# field cannot silently become a Codex setting just because it has a similar
# name on another harness.
CODEX_REQUIRED_RUNG_METADATA = {
    "junior": {"model": "gpt-5.6-luna", "effort": "max"},
    "escalation": {"model": "gpt-5.6-astra", "effort": "low"},
}
CODEX_CLAUDE_ONLY_FIELDS = ("tools", "omitClaudeMd", "maxTurns")
CODEX_SUPPORTED_FIELDS = (
    "name",
    "description",
    "developer_instructions",
    "model",
    "model_reasoning_effort",
)


def _split_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    """Return (frontmatter mapping, body text after the closing fence)."""
    text = path.read_text(encoding="utf-8")
    fm = _frontmatter(path)
    if not text.startswith("---"):
        return fm, text.strip() + "\n"
    end = text.find("\n---", 3)
    if end < 0:
        return fm, text.strip() + "\n"
    rest = text[end + 4 :]
    _, _, body = rest.partition("\n")
    return fm, body.strip() + "\n"


def _toml_basic(value: str) -> str:
    """A TOML single-line basic string."""
    out = value.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return f'"{out}"'


def _toml_multiline(value: str) -> str:
    """A TOML multi-line basic string, safe for prose with quotes."""
    out = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    if out.endswith('"'):
        out = out[:-1] + '\\"'
    return '"""\n' + out + '"""'


def _owned_codex_text(payload: str) -> str:
    """Prefix generated text with an ownership marker and payload digest."""
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return f"{CODEX_OWNER_MARKER}\n{CODEX_DIGEST_PREFIX}{digest}\n{payload}"


def _codex_ownership(text: str) -> str | None:
    """Return ``managed``, ``modified``, or ``None`` for legacy text."""
    lines = text.splitlines(keepends=True)
    if len(lines) < 3 or lines[0].rstrip("\r\n") != CODEX_OWNER_MARKER:
        return None
    digest_line = lines[1].rstrip("\r\n")
    if not digest_line.startswith(CODEX_DIGEST_PREFIX):
        return "modified"
    digest = digest_line[len(CODEX_DIGEST_PREFIX) :]
    if not re.fullmatch(r"[0-9a-f]{64}", digest):
        return "modified"
    payload = "".join(lines[2:])
    expected = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return "managed" if digest == expected else "modified"


def _atomic_write_text(path: Path, content: str) -> None:
    """Replace ``path`` atomically using a temporary file in its directory."""
    path.parent.mkdir(parents=True, exist_ok=True)
    old_mode: int | None = None
    try:
        old_mode = path.stat().st_mode & 0o777
    except OSError:
        pass
    fd, temp_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=str(path.parent)
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if old_mode is not None:
            os.chmod(temp_name, old_mode)
        os.replace(temp_name, path)
    finally:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass


def codex_rungs() -> dict[str, dict]:
    """The `codex` platform block of effort-models.json."""
    if not EFFORT_MODELS.is_file():
        return {}
    data = json.loads(EFFORT_MODELS.read_text(encoding="utf-8"))
    platforms = data.get("platforms")
    if not isinstance(platforms, dict):
        return {}
    codex = platforms.get("codex")
    return codex if isinstance(codex, dict) else {}


def validate_codex_rungs(rungs: dict[str, dict]) -> list[str]:
    """Return errors for stale or unsafe Codex role metadata.

    The model and effort values are a checked interface, rather than a best
    effort fallback.  A typo here would otherwise generate a valid-looking
    TOML file that dispatches the wrong rung.
    """
    issues: list[str] = []
    for rung, expected in CODEX_REQUIRED_RUNG_METADATA.items():
        spec = rungs.get(rung)
        if not isinstance(spec, dict):
            issues.append(f"missing platforms.codex.{rung} metadata")
            continue
        for key, value in expected.items():
            actual = spec.get(key)
            if actual != value:
                issues.append(
                    f"platforms.codex.{rung}.{key}={actual!r}; expected {value!r}"
                )

    capabilities = rungs.get("capabilities")
    if not isinstance(capabilities, dict):
        issues.append("missing platforms.codex.capabilities metadata")
    else:
        supported = capabilities.get("supported_fields")
        if supported != list(CODEX_SUPPORTED_FIELDS):
            issues.append(
                "platforms.codex.capabilities.supported_fields does not match "
                "the native Codex renderer"
            )
        omitted = capabilities.get("omitted_source_fields")
        if not isinstance(omitted, list) or any(
            field not in omitted for field in CODEX_CLAUDE_ONLY_FIELDS
        ):
            issues.append(
                "platforms.codex.capabilities.omitted_source_fields must include "
                "tools, omitClaudeMd, maxTurns"
            )
        if capabilities.get("diagnostic_mode") != "comments":
            issues.append(
                "platforms.codex.capabilities.diagnostic_mode must be 'comments'"
            )
    return issues


def _role_rung(agent: Path, frontmatter: dict[str, str]) -> str:
    """Read portable ``rung`` metadata, with a legacy filename fallback."""
    stem = agent.name.removesuffix(".agent.md")
    rung = frontmatter.get("rung")
    if rung is None:
        # Keep old source files readable while all canonical roles carry the
        # explicit field.  Once present, an invalid value is an error rather
        # than silently routing the role to junior.
        return "escalation" if stem in CODEX_ESCALATION_AGENTS else "junior"
    if rung not in CODEX_REQUIRED_RUNG_METADATA:
        raise ValueError(f"agents/{agent.name}: unsupported rung {rung!r}")
    return rung


def _codex_capabilities(rungs: dict[str, dict]) -> dict:
    capabilities = rungs.get("capabilities")
    return capabilities if isinstance(capabilities, dict) else {}


def codex_role_diagnostics(agent: Path, rungs: dict[str, dict]) -> list[str]:
    """Describe source controls intentionally omitted from a Codex artifact."""
    fm, _ = _split_frontmatter(agent)
    capabilities = _codex_capabilities(rungs)
    omitted = capabilities.get("omitted_source_fields")
    if not isinstance(omitted, list):
        omitted = list(CODEX_CLAUDE_ONLY_FIELDS)
    omitted_names = ", ".join(str(field) for field in omitted)
    present = [field for field in omitted if field in fm]
    present_note = (
        "present in this source: " + ", ".join(str(field) for field in present)
        if present
        else "none are present in this source"
    )
    return [
        "Codex capability diagnostics: omitted Claude-only source controls: "
        f"{omitted_names} ({present_note}).",
        "Codex capability diagnostics: source model/effort are overridden by "
        "the validated platforms.codex rung metadata.",
    ]


def render_codex_agent(agent: Path, rungs: dict[str, dict]) -> str:
    """Render one shared agent file as a Codex agent TOML."""
    issues = validate_codex_rungs(rungs)
    if issues:
        raise ValueError("invalid Codex role metadata: " + "; ".join(issues))
    fm, body = _split_frontmatter(agent)
    stem = agent.name.removesuffix(".agent.md")
    name = fm.get("name") or stem
    rung = _role_rung(agent, fm)
    spec = rungs.get(rung) or {}
    model = spec.get("model", "")
    effort = spec.get("effort", "")
    diagnostics = codex_role_diagnostics(agent, rungs)
    payload = (
        f"# Generated by scripts/install.py from agents/{agent.name}\n"
        f"# Rung: {rung} (effort-models.json → platforms.codex.{rung})\n"
        "# Edit the agent file, not this one.\n"
        + "".join(f"# {diagnostic}\n" for diagnostic in diagnostics)
        + f"name = {_toml_basic(name)}\n"
        + f"description = {_toml_basic(fm.get('description', ''))}\n"
        + f"developer_instructions = {_toml_multiline(body)}\n"
        + f"model = {_toml_basic(model)}\n"
        + f"model_reasoning_effort = {_toml_basic(effort)}\n"
    )
    return _owned_codex_text(payload)


def render_codex_host_rules() -> str:
    """Concatenate AGENTS.md, host.md, and harness/codex/codex.md from HOST.

    Same order as the former ``sync_host_rules.codex_plan()``. Missing sources
    are skipped. In-tree pointers stay relative here;
    ``codex_host_rules_file`` absolutises them for ``$CODEX_HOME``.
    """
    parts = [CODEX_HOST_RULES_BANNER]
    for name in CODEX_HOST_RULE_SOURCES:
        path = HOST / name
        if path.is_file():
            parts.append(path.read_text(encoding="utf-8").strip())
    if len(parts) == 1:
        return ""
    return "\n\n".join(parts) + "\n"


def codex_host_rules_file() -> list[tuple[Path, str]]:
    """`$CODEX_HOME/AGENTS.md` with in-tree pointers made absolute.

    Codex reads this copy from outside the repo, where `` `../ `` resolves
    to nothing, so the absolute form is written here rather than into git.
    """
    body = render_codex_host_rules()
    if not body:
        return []
    return [
        (
            CODEX_HOME / "AGENTS.md",
            _owned_codex_text(body.replace("`../", f"`{HOST}/")),
        )
    ]


def codex_agent_files() -> list[tuple[Path, str]]:
    """(destination path, rendered content) for every shared agent."""
    if not AGENTS.is_dir():
        return []
    rungs = codex_rungs()
    issues = validate_codex_rungs(rungs)
    if issues:
        raise ValueError("invalid Codex role metadata: " + "; ".join(issues))
    out: list[tuple[Path, str]] = []
    for agent in sorted(AGENTS.glob("*.agent.md")):
        stem = agent.name.removesuffix(".agent.md")
        out.append((CODEX_HOME / "agents" / f"{stem}.toml", render_codex_agent(agent, rungs)))
    return out


def _known_codex_symlink_target(dest: Path) -> Path | None:
    """Return the exact legacy target that this destination may replace."""
    if dest == CODEX_HOME / "AGENTS.md":
        # Older installers linked this file to the portable host rules. Keep
        # the generated copy in place when that exact link is encountered.
        return HOST_RULES
    agents_dir = CODEX_HOME / "agents"
    if dest.parent == agents_dir and dest.suffix == ".toml":
        source = AGENTS / f"{dest.stem}.agent.md"
        return source if source.is_file() else None
    return None


def apply_codex_agents(*, check: bool) -> list[tuple[str, str]]:
    """Write (or check) the generated Codex agent TOML files."""
    if not CODEX_HOME_SET or not CODEX_HOME.is_dir():
        return [("Codex shared agents (*.toml)", "skipped")]
    results: list[tuple[str, str]] = []
    try:
        generated = codex_host_rules_file() + codex_agent_files()
    except ValueError as exc:
        return [("Codex role model metadata", f"conflict: {exc}")]
    for dest, content in generated:
        label = (
            "Codex host rules AGENTS.md"
            if dest.name == "AGENTS.md"
            else f"Codex agent {dest.name}"
        )
        known_symlink = False
        if dest.is_symlink():
            # Only the exact links emitted by an older installer may be
            # replaced. A symlink into this checkout is not ownership proof.
            managed_target = _known_codex_symlink_target(dest)
            try:
                exact = managed_target is not None and dest.resolve() == managed_target.resolve()
            except OSError:
                exact = False
            if not exact or check:
                results.append((label, "conflict"))
                continue
            known_symlink = True
        if dest.exists() and not dest.is_file():
            results.append((label, "conflict"))
            continue
        current = dest.read_text(encoding="utf-8") if dest.is_file() else None
        if current == content:
            if dest.is_symlink():
                # An exact legacy link is still retired in apply mode so the
                # generated artifact owns its destination going forward.
                _atomic_write_text(dest, content)
                results.append((label, "updated"))
            else:
                results.append((label, "ok"))
            continue
        if check:
            results.append((label, "stale" if current is not None else "missing"))
            continue
        if current is not None and not known_symlink and _codex_ownership(current) != "managed":
            results.append((label, "conflict"))
            continue
        _atomic_write_text(dest, content)
        results.append((label, "updated" if current is not None else "created"))
    return results


# ---------------------------------------------------------------------------
# Cursor native agent markdown
# ---------------------------------------------------------------------------
#
# Cursor reads `~/.cursor/agents/<name>.md`. The shared source files carry
# Claude frontmatter (`model: opus`, `tools:`, `omitClaudeMd`, `maxTurns`).
# Live 2026-09-20: that `model: opus` is resolved to
# `claude-opus-5-thinking-high` at `subagentStart` even when the Task call
# passed `inherit`, and the Cursor family gate denies the spawn. So Cursor
# gets generated markdown with an in-family slug, written rather than
# linked, with the same ownership/conflict rules as Codex TOML.

CURSOR_OWNER_MARKER = "<!-- coding-agent-config installer ownership: cursor-v1 -->"
CURSOR_DIGEST_PREFIX = "<!-- coding-agent-config installer digest: sha256:"
CURSOR_REQUIRED_RUNG_METADATA = {
    "junior": {"model": "grok-4.6", "effort": "low"},
    "escalation": {"model": "grok-4.6", "effort": "high"},
}
CURSOR_CLAUDE_ONLY_FIELDS = ("tools", "omitClaudeMd", "maxTurns", "effort")
CURSOR_SUPPORTED_FIELDS = ("name", "description", "model")


def cursor_rungs() -> dict[str, dict]:
    """The `cursor` platform block of effort-models.json."""
    if not EFFORT_MODELS.is_file():
        return {}
    data = json.loads(EFFORT_MODELS.read_text(encoding="utf-8"))
    platforms = data.get("platforms")
    if not isinstance(platforms, dict):
        return {}
    cursor = platforms.get("cursor")
    return cursor if isinstance(cursor, dict) else {}


def validate_cursor_rungs(rungs: dict[str, dict]) -> list[str]:
    """Return errors for stale or unsafe Cursor role metadata."""
    issues: list[str] = []
    for rung, expected in CURSOR_REQUIRED_RUNG_METADATA.items():
        spec = rungs.get(rung)
        if not isinstance(spec, dict):
            issues.append(f"missing platforms.cursor.{rung} metadata")
            continue
        for key, value in expected.items():
            actual = spec.get(key)
            if actual != value:
                issues.append(
                    f"platforms.cursor.{rung}.{key}={actual!r}; expected {value!r}"
                )
    capabilities = rungs.get("capabilities")
    if not isinstance(capabilities, dict):
        issues.append("missing platforms.cursor.capabilities metadata")
    else:
        supported = capabilities.get("supported_fields")
        if supported != list(CURSOR_SUPPORTED_FIELDS):
            issues.append(
                "platforms.cursor.capabilities.supported_fields does not match "
                "the native Cursor renderer"
            )
        omitted = capabilities.get("omitted_source_fields")
        if not isinstance(omitted, list) or any(
            field not in omitted for field in CURSOR_CLAUDE_ONLY_FIELDS
        ):
            issues.append(
                "platforms.cursor.capabilities.omitted_source_fields must include "
                "tools, omitClaudeMd, maxTurns, effort"
            )
        if capabilities.get("diagnostic_mode") != "html_comments":
            issues.append(
                "platforms.cursor.capabilities.diagnostic_mode must be 'html_comments'"
            )
    return issues


def cursor_model_slug(spec: dict) -> str:
    """Compose the live Cursor Task slug from rung model + effort."""
    model = str(spec.get("model") or "").strip()
    effort = str(spec.get("effort") or "").strip()
    if not model:
        return ""
    if model.startswith("cursor-") or model in {"inherit", "inherit-parent", "auto"}:
        return model
    if effort:
        return f"cursor-{model}-{effort}"
    return f"cursor-{model}"


def _yaml_flow_scalar(value: str) -> str:
    """A double-quoted YAML scalar safe for one-line frontmatter values."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _cursor_capabilities(rungs: dict[str, dict]) -> dict:
    capabilities = rungs.get("capabilities")
    return capabilities if isinstance(capabilities, dict) else {}


def cursor_role_diagnostics(agent: Path, rungs: dict[str, dict]) -> list[str]:
    """Describe source controls omitted from a Cursor artifact."""
    fm, _ = _split_frontmatter(agent)
    capabilities = _cursor_capabilities(rungs)
    omitted = capabilities.get("omitted_source_fields")
    if not isinstance(omitted, list):
        omitted = list(CURSOR_CLAUDE_ONLY_FIELDS)
    omitted_names = ", ".join(str(field) for field in omitted)
    present = [field for field in omitted if field in fm]
    present_note = (
        "present in this source: " + ", ".join(str(field) for field in present)
        if present
        else "none are present in this source"
    )
    return [
        "Cursor capability diagnostics: omitted Claude-only source controls: "
        f"{omitted_names} ({present_note}).",
        "Cursor capability diagnostics: source model/effort are overridden by "
        "the validated platforms.cursor rung metadata.",
    ]


def _owned_cursor_text(payload: str) -> str:
    """Insert ownership comments after YAML frontmatter."""
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    markers = (
        f"{CURSOR_OWNER_MARKER}\n"
        f"{CURSOR_DIGEST_PREFIX}{digest} -->\n"
    )
    if payload.startswith("---"):
        end = payload.find("\n---\n")
        if end >= 0:
            head = payload[: end + 5]
            rest = payload[end + 5 :]
            if rest.startswith("\n"):
                rest = rest[1:]
            return head + "\n" + markers + rest
    return markers + payload


def _cursor_ownership(text: str) -> str | None:
    """Return ``managed``, ``modified``, or ``None`` for legacy text."""
    owner = CURSOR_OWNER_MARKER
    digest_re = re.compile(
        re.escape(CURSOR_DIGEST_PREFIX) + r"([0-9a-f]{64}) -->"
    )
    if owner not in text:
        return None
    match = digest_re.search(text)
    if match is None:
        return "modified"
    payload = text.replace(owner + "\n", "", 1)
    payload = payload.replace(match.group(0) + "\n", "", 1)
    expected = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return "managed" if match.group(1) == expected else "modified"


def render_cursor_agent(agent: Path, rungs: dict[str, dict]) -> str:
    """Render one shared agent file as Cursor-native markdown."""
    issues = validate_cursor_rungs(rungs)
    if issues:
        raise ValueError("invalid Cursor role metadata: " + "; ".join(issues))
    fm, body = _split_frontmatter(agent)
    stem = agent.name.removesuffix(".agent.md")
    name = fm.get("name") or stem
    rung = _role_rung(agent, fm)
    spec = rungs.get(rung) or {}
    slug = cursor_model_slug(spec)
    description = fm.get("description", "").replace("\n", " ").strip()
    diagnostics = cursor_role_diagnostics(agent, rungs)
    diag_block = "".join(f"<!-- {diagnostic} -->\n" for diagnostic in diagnostics)
    payload = (
        "---\n"
        f"name: {name}\n"
        f"description: {_yaml_flow_scalar(description)}\n"
        f"model: {slug}\n"
        "---\n\n"
        f"{diag_block}\n"
        f"{body}"
    )
    return _owned_cursor_text(payload)


def cursor_agent_files() -> list[tuple[Path, str]]:
    """(destination path, rendered content) for every shared agent."""
    if not AGENTS.is_dir():
        return []
    rungs = cursor_rungs()
    issues = validate_cursor_rungs(rungs)
    if issues:
        raise ValueError("invalid Cursor role metadata: " + "; ".join(issues))
    dest_dir = HOME / ".cursor" / "agents"
    out: list[tuple[Path, str]] = []
    for agent in sorted(AGENTS.glob("*.agent.md")):
        stem = agent.name.removesuffix(".agent.md")
        out.append((dest_dir / f"{stem}.md", render_cursor_agent(agent, rungs)))
    return out


def _known_cursor_symlink_target(dest: Path) -> Path | None:
    """Return the exact legacy target that this destination may replace."""
    agents_dir = HOME / ".cursor" / "agents"
    if dest.parent == agents_dir and dest.suffix == ".md":
        source = AGENTS / f"{dest.stem}.agent.md"
        return source if source.is_file() else None
    return None


def apply_cursor_agents(*, check: bool) -> list[tuple[str, str]]:
    """Write (or check) generated Cursor agent markdown files."""
    cursor_home = HOME / ".cursor"
    if not cursor_home.is_dir():
        return [("Cursor shared agents (*.md)", "skipped")]
    results: list[tuple[str, str]] = []
    try:
        generated = cursor_agent_files()
    except ValueError as exc:
        return [("Cursor role model metadata", f"conflict: {exc}")]
    for dest, content in generated:
        label = f"Cursor agent {dest.name}"
        known_symlink = False
        if dest.is_symlink():
            managed_target = _known_cursor_symlink_target(dest)
            try:
                exact = (
                    managed_target is not None
                    and dest.resolve() == managed_target.resolve()
                )
            except OSError:
                exact = False
            if not exact or check:
                results.append((label, "conflict"))
                continue
            known_symlink = True
        if dest.exists() and not dest.is_file():
            results.append((label, "conflict"))
            continue
        current = dest.read_text(encoding="utf-8") if dest.is_file() else None
        if current == content:
            if dest.is_symlink():
                _atomic_write_text(dest, content)
                results.append((label, "updated"))
            else:
                results.append((label, "ok"))
            continue
        if check:
            results.append((label, "stale" if current is not None else "missing"))
            continue
        if current is not None and not known_symlink and _cursor_ownership(current) != "managed":
            results.append((label, "conflict"))
            continue
        _atomic_write_text(dest, content)
        results.append((label, "updated" if current is not None else "created"))
    return results


# ---------------------------------------------------------------------------
# Antigravity native agent markdown & hooks
# ---------------------------------------------------------------------------
#
# Antigravity discovers global subagents in `~/.gemini/config/agents/*.md`.
# Antigravity requires `subagent: true` in the YAML frontmatter to treat an
# agent as an invocable subagent, and `model: opus` triggers off-family
# denials. So Antigravity gets generated markdown carrying in-family models
# (flash) and effort levels from effort-models.json, written rather than
# linked, with the same ownership/conflict rules as Cursor.
# Lifecycle hooks in `~/.gemini/config/hooks.json` are also managed with absolute paths.

ANTIGRAVITY_OWNER_MARKER = "<!-- coding-agent-config installer ownership: antigravity-v1 -->"
ANTIGRAVITY_DIGEST_PREFIX = "<!-- coding-agent-config installer digest: sha256:"
ANTIGRAVITY_REQUIRED_RUNG_METADATA = {
    "junior": {"model": "flash", "effort": "medium"},
    "escalation": {"model": "flash", "effort": "high"},
}
ANTIGRAVITY_CLAUDE_ONLY_FIELDS = ("tools", "omitClaudeMd", "maxTurns")
ANTIGRAVITY_SUPPORTED_FIELDS = (
    "name",
    "description",
    "model",
    "effort",
    "reasoningEffort",
    "subagent",
)


def antigravity_rungs() -> dict[str, dict]:
    """The `antigravity` platform block of effort-models.json."""
    if not EFFORT_MODELS.is_file():
        return {}
    data = json.loads(EFFORT_MODELS.read_text(encoding="utf-8"))
    platforms = data.get("platforms")
    if not isinstance(platforms, dict):
        return {}
    antigravity = platforms.get("antigravity")
    return antigravity if isinstance(antigravity, dict) else {}


def validate_antigravity_rungs(rungs: dict[str, dict]) -> list[str]:
    """Return errors for stale or unsafe Antigravity role metadata."""
    issues: list[str] = []
    for rung, expected in ANTIGRAVITY_REQUIRED_RUNG_METADATA.items():
        spec = rungs.get(rung)
        if not isinstance(spec, dict):
            issues.append(f"missing platforms.antigravity.{rung} metadata")
            continue
        for key, value in expected.items():
            actual = spec.get(key)
            if actual != value:
                issues.append(
                    f"platforms.antigravity.{rung}.{key}={actual!r}; expected {value!r}"
                )
    capabilities = rungs.get("capabilities")
    if not isinstance(capabilities, dict):
        issues.append("missing platforms.antigravity.capabilities metadata")
    else:
        supported = capabilities.get("supported_fields")
        if supported != list(ANTIGRAVITY_SUPPORTED_FIELDS):
            issues.append(
                "platforms.antigravity.capabilities.supported_fields does not match "
                "the native Antigravity renderer"
            )
        omitted = capabilities.get("omitted_source_fields")
        if not isinstance(omitted, list) or any(
            field not in omitted for field in ANTIGRAVITY_CLAUDE_ONLY_FIELDS
        ):
            issues.append(
                "platforms.antigravity.capabilities.omitted_source_fields must include "
                "tools, omitClaudeMd, maxTurns"
            )
        if capabilities.get("diagnostic_mode") != "html_comments":
            issues.append(
                "platforms.antigravity.capabilities.diagnostic_mode must be 'html_comments'"
            )
    return issues


def _antigravity_capabilities(rungs: dict[str, dict]) -> dict:
    capabilities = rungs.get("capabilities")
    return capabilities if isinstance(capabilities, dict) else {}


def antigravity_role_diagnostics(agent: Path, rungs: dict[str, dict]) -> list[str]:
    """Describe source controls omitted from an Antigravity artifact."""
    fm, _ = _split_frontmatter(agent)
    capabilities = _antigravity_capabilities(rungs)
    omitted = capabilities.get("omitted_source_fields")
    if not isinstance(omitted, list):
        omitted = list(ANTIGRAVITY_CLAUDE_ONLY_FIELDS)
    omitted_names = ", ".join(str(field) for field in omitted)
    present = [field for field in omitted if field in fm]
    present_note = (
        "present in this source: " + ", ".join(str(field) for field in present)
        if present
        else "none are present in this source"
    )
    return [
        "Antigravity capability diagnostics: omitted Claude-only source controls: "
        f"{omitted_names} ({present_note}).",
        "Antigravity capability diagnostics: source model/effort are overridden by "
        "the validated platforms.antigravity rung metadata.",
    ]


def _owned_antigravity_text(payload: str) -> str:
    """Insert ownership comments after YAML frontmatter."""
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    markers = (
        f"{ANTIGRAVITY_OWNER_MARKER}\n"
        f"{ANTIGRAVITY_DIGEST_PREFIX}{digest} -->\n"
    )
    if payload.startswith("---"):
        end = payload.find("\n---\n")
        if end >= 0:
            head = payload[: end + 5]
            rest = payload[end + 5 :]
            if rest.startswith("\n"):
                rest = rest[1:]
            return head + "\n" + markers + rest
    return markers + payload


def _antigravity_ownership(text: str) -> str | None:
    """Return ``managed``, ``modified``, or ``None`` for legacy text."""
    owner = ANTIGRAVITY_OWNER_MARKER
    digest_re = re.compile(
        re.escape(ANTIGRAVITY_DIGEST_PREFIX) + r"([0-9a-f]{64}) -->"
    )
    if owner not in text:
        return None
    match = digest_re.search(text)
    if match is None:
        return "modified"
    payload = text.replace(owner + "\n", "", 1)
    payload = payload.replace(match.group(0) + "\n", "", 1)
    expected = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return "managed" if match.group(1) == expected else "modified"


def render_antigravity_agent(agent: Path, rungs: dict[str, dict]) -> str:
    """Render one shared agent file as Antigravity-native markdown."""
    issues = validate_antigravity_rungs(rungs)
    if issues:
        raise ValueError("invalid Antigravity role metadata: " + "; ".join(issues))
    fm, body = _split_frontmatter(agent)
    stem = agent.name.removesuffix(".agent.md")
    name = fm.get("name") or stem
    rung = _role_rung(agent, fm)
    spec = rungs.get(rung) or {}
    model = str(spec.get("model") or "").strip()
    effort = str(spec.get("effort") or "").strip()
    description = fm.get("description", "").replace("\n", " ").strip()
    diagnostics = antigravity_role_diagnostics(agent, rungs)
    diag_block = "".join(f"<!-- {diagnostic} -->\n" for diagnostic in diagnostics)
    payload = (
        "---\n"
        f"name: {name}\n"
        f"description: {_yaml_flow_scalar(description)}\n"
        f"model: {model}\n"
        f"effort: {effort}\n"
        f"reasoningEffort: {effort}\n"
        "subagent: true\n"
        "---\n\n"
        f"{diag_block}\n"
        f"{body}"
    )
    return _owned_antigravity_text(payload)


def antigravity_agent_files() -> list[tuple[Path, str]]:
    """(destination path, rendered content) for every shared agent."""
    if not AGENTS.is_dir():
        return []
    rungs = antigravity_rungs()
    issues = validate_antigravity_rungs(rungs)
    if issues:
        raise ValueError("invalid Antigravity role metadata: " + "; ".join(issues))
    dest_dir = HOME / ".gemini" / "config" / "agents"
    out: list[tuple[Path, str]] = []
    for agent in sorted(AGENTS.glob("*.agent.md")):
        stem = agent.name.removesuffix(".agent.md")
        out.append((dest_dir / f"{stem}.md", render_antigravity_agent(agent, rungs)))
    return out


def _known_antigravity_symlink_target(dest: Path) -> Path | None:
    """Return the exact legacy target that this destination may replace."""
    agents_dir = HOME / ".gemini" / "config" / "agents"
    if dest.parent == agents_dir and dest.suffix == ".md":
        source = AGENTS / f"{dest.stem}.agent.md"
        return source if source.is_file() else None
    return None


def apply_antigravity_agents(*, check: bool) -> list[tuple[str, str]]:
    """Write (or check) generated Antigravity agent markdown files."""
    gemini_config = HOME / ".gemini" / "config"
    if not gemini_config.is_dir():
        return [("Antigravity shared agents (*.md)", "skipped")]
    results: list[tuple[str, str]] = []
    try:
        generated = antigravity_agent_files()
    except ValueError as exc:
        return [("Antigravity role model metadata", f"conflict: {exc}")]
    for dest, content in generated:
        label = f"Antigravity agent {dest.name}"
        known_symlink = False
        if dest.is_symlink():
            managed_target = _known_antigravity_symlink_target(dest)
            try:
                canonical_target = HOME / ".agent-rules" / "agents" / f"{dest.stem}.agent.md"
                exact = (
                    managed_target is not None
                    and (
                        dest.resolve() == managed_target.resolve()
                        or (canonical_target.is_file() and dest.resolve() == canonical_target.resolve())
                    )
                )
            except OSError:
                exact = False
            if not exact or check:
                results.append((label, "conflict"))
                continue
            known_symlink = True
        if dest.exists() and not dest.is_file():
            results.append((label, "conflict"))
            continue
        current = dest.read_text(encoding="utf-8") if dest.is_file() else None
        if current == content:
            if dest.is_symlink():
                _atomic_write_text(dest, content)
                results.append((label, "updated"))
            else:
                results.append((label, "ok"))
            continue
        if check:
            results.append((label, "stale" if current is not None else "missing"))
            continue
        if current is not None and not known_symlink and _antigravity_ownership(current) != "managed":
            results.append((label, "conflict"))
            continue
        _atomic_write_text(dest, content)
        results.append((label, "updated" if current is not None else "created"))
    return results


def render_antigravity_hooks() -> dict:
    """Antigravity lifecycle hooks with absolute paths."""
    canonical = HOME / ".agent-rules" / "harness" / "antigravity"
    harness = canonical if canonical.is_dir() else (HOST / "harness" / "antigravity")
    return {
        "shell-guard": {
            "PreToolUse": [
                {
                    "matcher": "run_command",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"/usr/bin/python3 {harness / 'before-shell.py'}",
                            "timeout": 15,
                        }
                    ],
                }
            ]
        },
        "model-family-guard": {
            "PreToolUse": [
                {
                    "matcher": "invoke_subagent",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f"/usr/bin/python3 {harness / 'guard-model-family.py'}",
                            "timeout": 15,
                        }
                    ],
                }
            ]
        },
        "candidate-reminders": {
            "PreInvocation": [
                {
                    "type": "command",
                    "command": f"/usr/bin/python3 {harness / 'pre-invocation.py'}",
                    "timeout": 15,
                }
            ]
        },
        "session-stop": {
            "Stop": [
                {
                    "type": "command",
                    "command": f"/usr/bin/python3 {harness / 'stop.py'}",
                    "timeout": 15,
                }
            ]
        },
    }


def apply_antigravity_hooks(*, check: bool) -> list[tuple[str, str]]:
    """Write (or check) Antigravity hooks.json with absolute script paths."""
    gemini_config = HOME / ".gemini" / "config"
    if not gemini_config.is_dir():
        return [("Antigravity hooks.json", "skipped")]
    target = gemini_config / "hooks.json"
    desired = json.dumps(render_antigravity_hooks(), indent=2) + "\n"
    current = target.read_text(encoding="utf-8") if target.is_file() else None
    label = "Antigravity hooks.json"
    if current == desired:
        return [(label, "ok")]
    if check:
        return [(label, "stale" if current is not None else "missing")]
    _atomic_write_text(target, desired)
    return [(label, "updated" if current is not None else "created")]

  
# ---------------------------------------------------------------------------
# Cursor hooks.json — same job list as Codex, Cursor event names
# ---------------------------------------------------------------------------
#
# Codex's `$CODEX_HOME/hooks.json` is the static dialect of this list
# (`harness/codex/codex-hooks.json`). Cursor cannot use that file: event
# names, failClosed, and matcher fields differ. One job list, two
# renderers. Cursor-only jobs (family gate, subagentStop) have no Codex
# event.

CURSOR_HOOKS_PYTHON = "/usr/bin/python3"
CURSOR_HOOKS_OWNERSHIP = "cursor-hooks-v1"
CURSOR_HOOKS_META_KEY = "_codingAgentConfig"
# Path prefix baked into the tracked `.cursor/hooks.json` in this repo.
TRACKED_CURSOR_HOST = Path("/home/itec/emanuele/.agent-rules")


def cursor_hook_jobs() -> list[dict[str, object]]:
    """Lifecycle jobs shared with Codex, plus Cursor-only family/subagent jobs.

    `codex_event` / `codex_script` are None for Cursor-only jobs. Callers
    rely on `cursor_event` + `cursor_script` being present on every row.
    """
    return [
        {
            "name": "shell-guard",
            "codex_event": "PreToolUse",
            "codex_script": "pre-tool-use.py",
            "cursor_event": "beforeShellExecution",
            "cursor_script": "before-shell.py",
            "timeout": 45,
            "fail_closed": True,
        },
        {
            "name": "session-start",
            "codex_event": "SessionStart",
            "codex_script": "session-start.py",
            "cursor_event": "sessionStart",
            "cursor_script": "session-start.py",
            "timeout": 15,
        },
        {
            "name": "prompt-submit",
            "codex_event": "UserPromptSubmit",
            "codex_script": "user-prompt-submit.py",
            "cursor_event": "beforeSubmitPrompt",
            "cursor_script": "before-submit-prompt.py",
            "timeout": 10,
        },
        {
            "name": "stop",
            "codex_event": "Stop",
            "codex_script": "stop.py",
            "cursor_event": "stop",
            "cursor_script": "stop.py",
            "timeout": 15,
        },
        {
            "name": "pre-compact",
            "codex_event": "PreCompact",
            "codex_script": "pre-compact.py",
            "cursor_event": "preCompact",
            "cursor_script": "pre-compact.py",
            "timeout": 10,
        },
        {
            "name": "model-family",
            "codex_event": None,
            "codex_script": None,
            "cursor_event": "preToolUse",
            "cursor_script": "before-task.py",
            "timeout": 45,
            "fail_closed": True,
            "matcher": "Task",
        },
        {
            "name": "model-family-subagent",
            "codex_event": None,
            "codex_script": None,
            "cursor_event": "subagentStart",
            "cursor_script": "before-task.py",
            "timeout": 45,
            "fail_closed": True,
        },
        {
            "name": "subagent-stop",
            "codex_event": None,
            "codex_script": None,
            "cursor_event": "subagentStop",
            "cursor_script": "subagent-stop.py",
            "timeout": 15,
        },
    ]


def _cursor_hook_command(host: Path, script: str) -> str:
    return f"{CURSOR_HOOKS_PYTHON} {host / 'harness' / 'cursor' / script}"


def _cursor_hook_entry(host: Path, job: dict[str, object]) -> dict[str, object]:
    entry: dict[str, object] = {
        "command": _cursor_hook_command(host, str(job["cursor_script"])),
        "timeout": int(job["timeout"]),
    }
    matcher = job.get("matcher")
    if isinstance(matcher, str) and matcher:
        entry["matcher"] = matcher
    if job.get("fail_closed"):
        entry["failClosed"] = True
    return entry


def _cursor_hooks_digest(hooks: dict[str, object]) -> str:
    payload = json.dumps(hooks, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def render_cursor_hooks(*, host: Path | None = None) -> dict[str, object]:
    """Return the managed Cursor hooks.json document for ``host``.

    Does not include user-owned extra hooks. The digest covers only
    ``hooks``. Callers merge extras before writing.
    """
    root = host if host is not None else HOST
    hooks: dict[str, list[dict[str, object]]] = {}
    for job in cursor_hook_jobs():
        event = str(job["cursor_event"])
        hooks.setdefault(event, []).append(_cursor_hook_entry(root, job))
    digest = _cursor_hooks_digest(hooks)
    return {
        "version": 1,
        "hooks": hooks,
        CURSOR_HOOKS_META_KEY: {
            "ownership": CURSOR_HOOKS_OWNERSHIP,
            "digest": digest,
        },
    }


def _hook_script_path(command: object) -> Path | None:
    if not isinstance(command, str) or not command.strip():
        return None
    parts = command.split()
    candidate = parts[-1]
    try:
        return Path(candidate)
    except (TypeError, ValueError):
        return None


def _is_managed_cursor_command(command: object, host: Path) -> bool:
    script = _hook_script_path(command)
    if script is None:
        return False
    try:
        resolved = script.resolve()
        cursor_dir = (host / "harness" / "cursor").resolve()
    except OSError:
        return str(script).startswith(str(host / "harness" / "cursor"))
    try:
        resolved.relative_to(cursor_dir)
        return True
    except ValueError:
        return False


def _split_cursor_hooks(
    hooks: object, host: Path
) -> tuple[dict[str, list], dict[str, list]]:
    """Return (managed_subset, user_extras) keyed by event name."""
    managed: dict[str, list] = {}
    extras: dict[str, list] = {}
    if not isinstance(hooks, dict):
        return managed, extras
    for event, entries in hooks.items():
        if not isinstance(event, str) or not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                extras.setdefault(event, []).append(entry)
                continue
            bucket = (
                managed if _is_managed_cursor_command(entry.get("command"), host) else extras
            )
            bucket.setdefault(event, []).append(entry)
    return managed, extras


def _merge_cursor_hooks(
    managed: dict[str, list], extras: dict[str, list]
) -> dict[str, list]:
    merged: dict[str, list] = {}
    for event, entries in managed.items():
        merged[event] = list(entries)
    for event, entries in extras.items():
        merged.setdefault(event, []).extend(entries)
    return merged


def _cursor_hooks_ownership(doc: dict, host: Path) -> str | None:
    """Return ``managed``, ``modified``, or ``None`` for a legacy file."""
    meta = doc.get(CURSOR_HOOKS_META_KEY)
    if not isinstance(meta, dict):
        return None
    if meta.get("ownership") != CURSOR_HOOKS_OWNERSHIP:
        return "modified"
    digest = meta.get("digest")
    if not isinstance(digest, str) or not re.fullmatch(r"[0-9a-f]{64}", digest):
        return "modified"
    managed, _ = _split_cursor_hooks(doc.get("hooks"), host)
    return "managed" if digest == _cursor_hooks_digest(managed) else "modified"


def _dumps_cursor_hooks(doc: dict[str, object]) -> str:
    return json.dumps(doc, indent=2) + "\n"


def _parse_cursor_hooks(text: str) -> dict | None:
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def _desired_cursor_hooks(host: Path, extras: dict[str, list]) -> dict[str, object]:
    rendered = render_cursor_hooks(host=host)
    hooks = rendered["hooks"]
    assert isinstance(hooks, dict)
    merged = _merge_cursor_hooks(hooks, extras)
    rendered["hooks"] = merged
    rendered[CURSOR_HOOKS_META_KEY] = {
        "ownership": CURSOR_HOOKS_OWNERSHIP,
        "digest": _cursor_hooks_digest(hooks),
    }
    return rendered


def apply_cursor_hooks(*, check: bool) -> list[tuple[str, str]]:
    """Write (or check) generated ``~/.cursor/hooks.json``, keeping user extras."""
    cursor_home = HOME / ".cursor"
    dest = cursor_home / "hooks.json"
    label = "Cursor hooks.json"
    results: list[tuple[str, str]] = []
    if not cursor_home.is_dir():
        return [(label, "skipped")]
    desired_managed = render_cursor_hooks(host=HOST)
    managed_hooks = desired_managed["hooks"]
    assert isinstance(managed_hooks, dict)

    if dest.is_symlink():
        if check:
            return [(label, "conflict")]
        return [(label, "conflict")]

    current_text = dest.read_text(encoding="utf-8") if dest.is_file() else None
    extras: dict[str, list] = {}
    ownership: str | None = None
    if current_text is not None:
        parsed = _parse_cursor_hooks(current_text)
        if parsed is None:
            return [(label, "conflict")]
        _, extras = _split_cursor_hooks(parsed.get("hooks"), HOST)
        ownership = _cursor_hooks_ownership(parsed, HOST)
        if ownership == "modified":
            return [(label, "conflict")]

    desired = _desired_cursor_hooks(HOST, extras)
    desired_text = _dumps_cursor_hooks(desired)
    if current_text == desired_text:
        results.append((label, "ok"))
    elif check:
        results.append((label, "stale" if current_text is not None else "missing"))
    else:
        _atomic_write_text(dest, desired_text)
        results.append((label, "updated" if current_text is not None else "created"))

    tracked = HOST.parent / ".cursor" / "hooks.json"
    if tracked.is_file():
        tracked_label = "tracked .cursor/hooks.json"
        expected = _dumps_cursor_hooks(render_cursor_hooks(host=TRACKED_CURSOR_HOST))
        try:
            tracked_text = tracked.read_text(encoding="utf-8")
        except OSError:
            results.append((tracked_label, "conflict"))
        else:
            results.append(
                (tracked_label, "ok" if tracked_text == expected else "stale")
            )
    return results


# ---------------------------------------------------------------------------
# MCP catalog → per-platform configs
# ---------------------------------------------------------------------------


def _cursor_entry(spec: dict) -> dict:
    """Cursor mcp.json entry from a catalog server spec."""
    if "url" in spec or "serverUrl" in spec:
        entry: dict = {"url": spec.get("url") or spec.get("serverUrl")}
        if "headers" in spec:
            entry["headers"] = spec["headers"]
        if "auth" in spec:
            entry["auth"] = spec["auth"]
        return entry
    entry = {"command": spec["command"]}
    if "args" in spec:
        entry["args"] = spec["args"]
    if "env" in spec:
        entry["env"] = spec["env"]
    if "envFile" in spec:
        entry["envFile"] = spec["envFile"]
    return entry


def _antigravity_entry(spec: dict) -> dict:
    """Antigravity mcp_config.json entry — remote servers use serverUrl."""
    if "url" in spec or "serverUrl" in spec:
        entry: dict = {"serverUrl": spec.get("serverUrl") or spec.get("url")}
        if "headers" in spec:
            entry["headers"] = spec["headers"]
        return entry
    entry = {"command": spec["command"]}
    if "args" in spec:
        entry["args"] = spec["args"]
    if "env" in spec:
        entry["env"] = spec["env"]
    return entry


def _claude_entry(spec: dict) -> dict:
    """Claude Code .mcp.json / ~/.claude.json mcpServers entry."""
    return _cursor_entry(spec)


def _read_json(path: Path) -> dict:
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def _write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


def upsert_mcp_servers(
    path: Path,
    key: str,
    catalog: dict[str, dict],
    render,
    *,
    check: bool,
) -> str:
    """Upsert catalog servers under `data[key]`. Returns a status token."""
    if not catalog:
        return "empty"
    data = _read_json(path)
    bucket = data.get(key)
    if not isinstance(bucket, dict):
        bucket = {}
    desired = {name: render(spec) for name, spec in catalog.items()}
    changed = False
    for name, entry in desired.items():
        if bucket.get(name) != entry:
            bucket[name] = entry
            changed = True
    data[key] = bucket
    if not changed and path.is_file():
        return "ok"
    if check:
        return "stale" if path.is_file() else "missing"
    _write_json(path, data)
    return "updated" if path.is_file() else "created"


def mcp_targets(catalog: dict[str, dict]) -> list[tuple[str, Path, str, object]]:
    """(label, path, json_key, render_fn) for each platform config we manage."""
    return [
        (
            "Cursor global MCP",
            HOME / ".cursor" / "mcp.json",
            "mcpServers",
            _cursor_entry,
        ),
        (
            "Antigravity global MCP",
            HOME / ".gemini" / "config" / "mcp_config.json",
            "mcpServers",
            _antigravity_entry,
        ),
        # Claude user-level MCP lives inside ~/.claude.json alongside credentials.
        # We only upsert the mcpServers key; everything else is left untouched.
        (
            "Claude Code user MCP (~/.claude.json)",
            HOME / ".claude.json",
            "mcpServers",
            _claude_entry,
        ),
    ]


def apply_mcp(*, check: bool) -> list[tuple[str, str]]:
    """Shared MCP catalog is unused; platform configs are left untouched."""
    return [("mcp.json shared servers", "skipped (no shared MCP catalog)")]


def _plugin_row_is_problem(status: str) -> bool:
    if status in {"ok", "absent (ok until shared MCP is added)"}:
        return False
    if status.startswith("empty"):
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report the farm's state without changing anything",
    )
    args = parser.parse_args()

    problems = 0

    plugin_rows = validate_plugin()
    if plugin_rows:
        print("Agent Plugins portable core:")
        for label, status in plugin_rows:
            print(f"{status:9} {label}")
            if _plugin_row_is_problem(status):
                problems += 1
        print()

    items = plan()
    width = max((len(str(i.link)) for i in items), default=40)

    for item in items:
        state = item.status()
        if state in {"missing", "wrong"} and not args.check:
            if apply(item):
                state = "created" if state == "missing" else "relinked"
            else:
                state = "conflict"
        if state in {"missing", "wrong", "conflict"}:
            problems += 1
        print(f"{state:9} {str(item.link):{width}}  {item.why}")

    print()
    for label, status in apply_cursor_agents(check=args.check):
        print(f"{status:9} {label}")
        if status in {"missing", "stale", "conflict"}:
            problems += 1
            
    print()
    for label, status in apply_cursor_hooks(check=args.check):
        print(f"{status:9} {label}")
        if status in {"missing", "stale", "conflict"}:
            problems += 1

    print()
    for label, status in apply_antigravity_agents(check=args.check):
        print(f"{status:9} {label}")
        if status in {"missing", "stale", "conflict"}:
            problems += 1

    print()
    for label, status in apply_antigravity_hooks(check=args.check):
        print(f"{status:9} {label}")
        if status in {"missing", "stale", "conflict"}:
            problems += 1

    print()
    for label, status in apply_codex_agents(check=args.check):
        print(f"{status:9} {label}")
        if status in {"missing", "stale", "conflict"}:
            problems += 1

    print()
    for label, status in apply_mcp(check=args.check):
        print(f"{status:9} {label}")
        if status in {"missing", "stale"}:
            problems += 1

    if args.check and problems:
        print(
            f"\n{problems} item(s) missing, wrong, stale or blocked. "
            "Run: python3 install.py",
            file=sys.stderr,
        )
        return 1
    if not args.check:
        conflicts = [i for i in items if i.status() == "conflict"]
        if conflicts:
            print(
                f"\n{len(conflicts)} path(s) hold a real file where a symlink belongs; "
                "left untouched, resolve by hand.",
                file=sys.stderr,
            )
            return 1
        if problems:
            print(
                f"\n{problems} Agent Plugins core problem(s); farm links may still be ok.",
                file=sys.stderr,
            )
            return 1
    print("\nsymlink farm: consistent")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
