#!/usr/bin/env python3
"""One-shot migration: CLAUDE.md SoT -> AGENTS.md SoT (pointstream layout).

Usage:
    python3 migrate_to_agents_md.py /path/to/repo [--name DISPLAY] [--guards JSON]

Idempotent enough to re-run: skips if CLAUDE.md already imports @AGENTS.md
unless --force is passed.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

HOST_SYNC = Path.home() / ".agent-rules" / "scripts" / "sync_agent_rules.py"

OLD_FRAMING = re.compile(
    r"\*\*This file is the only rule file to edit by hand\.\*\*.*?(?=\n## |\n# |\Z)",
    re.DOTALL,
)
GENERATED_BANNER = re.compile(
    r"^<!-- GENERATED from CLAUDE\.md by tools/sync_agent_rules\.py.*?\n\n",
    re.DOTALL,
)
HOST_BLOCK = re.compile(
    r"\n*<!-- host-rules:start.*?<!-- host-rules:end -->\n?", re.DOTALL
)
# Old 4DGStudy / snapshot-style host section without markers
OLD_HOST_TAIL = re.compile(
    r"\n+---\n+\n+# Host-wide rules\n.*\Z",
    re.DOTALL,
)
SHARED_IMPORT = re.compile(
    r"\n*@/home/itec/emanuele/\.agent-rules/shared\.md\n*",
)

NEW_FRAMING_CI = (
    "**This file is the only rule file to edit by hand.** Cursor, Antigravity,\n"
    "Codex and Copilot's cloud agent read `AGENTS.md` natively; `CLAUDE.md` is a\n"
    "thin wrapper that `@`-imports it, because Claude Code is the one agent with no\n"
    "AGENTS.md support. The `host-rules` block at the end,\n"
    "`.cursor/rules/cursor-harness.mdc` and `.github/copilot-instructions.md` are\n"
    "generated by `tools/sync_agent_rules.py` — edit this file outside that block,\n"
    "then re-run the script; CI fails the commit if they are stale.\n\n"
)

NEW_FRAMING_HAND = (
    "**This file is the only rule file to edit by hand.** Cursor, Antigravity,\n"
    "Codex and Copilot's cloud agent read `AGENTS.md` natively; `CLAUDE.md` is a\n"
    "thin wrapper that `@`-imports it, because Claude Code is the one agent with no\n"
    "AGENTS.md support. The `host-rules` block at the end,\n"
    "`.cursor/rules/cursor-harness.mdc` and `.github/copilot-instructions.md` are\n"
    "generated by `tools/sync_agent_rules.py` — edit this file outside that block,\n"
    "then re-run `python3 tools/sync_agent_rules.py` before committing (this repo\n"
    "has no pre-commit/CI gate for it yet).\n\n"
)

WORKFLOWS_README = """# Project workflows (slash commands)

Host-wide slash prompts live in `~/.agent-rules/workflows/` and are linked into
Cursor (`~/.cursor/commands/`) and Antigravity
(`~/.gemini/config/global_workflows/`) by `~/.agent-rules/scripts/install.py`.

Project-specific ones go here as plain `<name>.md` files (filename = `/name`).
`.cursor/commands` in this repo is a symlink onto this directory, so Cursor and
Antigravity share one tree. Claude Code does **not** read this path — its slash
surface is skills under `.claude/skills/`. Promote a workflow to a skill if it
must also auto-trigger for Claude.
"""

GITIGNORE_BLOCK = """
# Cross-agent project layout: real skills/agents under .claude/; .agents/
# holds symlinks plus the workflows tree Cursor and Antigravity share.
.agents/*
!.agents/agents
!.agents/skills
!.agents/workflows
!.agents/workflows/**

# Claude Code: local permission grants are machine-specific, not shared
.claude/settings.local.json
.claude/worktrees/
"""


def soft_claudeisms(text: str) -> str:
    text = text.replace(
        "as a background `Bash` (`run_in_background: true`), which\n"
        "notifies on exit",
        "as a background shell job (or the agent's background-launch\n"
        "equivalent), which notifies on exit",
    )
    text = text.replace(
        "see the global CLAUDE.md's waiting rule for why\n"
        "that loop can never terminate.",
        "see the host-wide waiting rule for why that loop can never terminate.",
    )
    text = text.replace(
        "and `Monitor` always has something fresh to match\non",
        "and any progress watcher always has something fresh to match on",
    )
    text = text.replace(
        "The `.claude/` directory (this file, `skills/`, `agents/`, `hooks/`,\n"
        "`settings.json`) is part of the working setup, not frozen. If during work we\n"
        "find a convention Claude gets wrong twice, a skill that would help, a hook\n"
        "worth adding, or a rule that's stale — add/update/remove it in `.claude/`\n"
        "right then. Note: edits to `settings.json`/hooks only take effect on the next\n"
        "session (open `/hooks` or restart to reload); skills and CLAUDE.md load fresh\n"
        "each session too, so prefer those for anything you want to rely on immediately.",
        "Agent config for this repo (`AGENTS.md`, `.claude/skills/`, `.claude/agents/`,\n"
        "hooks in `.claude/settings.json`, `.agent-guards.json`) is part of the working\n"
        "setup, not frozen. If a convention gets misapplied twice, a skill would help,\n"
        "or a rule is stale — update it then. Edits to `settings.json`/hooks take effect\n"
        "on the next session; `AGENTS.md` and skills load fresh each session.",
    )
    text = text.replace(
        "`.claude/` (this file, `agents/`, `skills/`, `hooks/`, `settings.json`) is part of the\n"
        "working setup, not frozen — if a convention gets misapplied twice, or a repeated\n"
        "debugging workflow (e.g. MoQ packetization) turns out to want its own skill, add it then.\n"
        "Edits to `settings.json`/hooks take effect next session; CLAUDE.md loads fresh each\n"
        "session.",
        "Agent config for this repo (`AGENTS.md`, `.claude/`, `.agent-guards.json`) is part of\n"
        "the working setup, not frozen — if a convention gets misapplied twice, or a repeated\n"
        "debugging workflow (e.g. MoQ packetization) turns out to want its own skill, add it\n"
        "then. Edits to `settings.json`/hooks take effect next session; `AGENTS.md` loads fresh\n"
        "each session.",
    )
    # Gaps section references to editing CLAUDE.md
    text = text.replace(
        "make. Until it (or a CI job) is adopted, run `python3 tools/sync_agent_rules.py\n"
        "  --check` by hand before committing rule changes.",
        "make. Until it (or a CI job) is adopted, run `python3 tools/sync_agent_rules.py\n"
        "  --check` by hand before committing `AGENTS.md` changes.",
    )
    text = text.replace(
        "There is no `.pre-commit-config.yaml` in this repo and CI does not run\n"
        "`tools/sync_agent_rules.py --check` — unlike pointstream/presley, nothing\n"
        "currently blocks a commit or a CI run on stale generated agent-rule files.\n"
        "If pre-commit gets adopted here later, add a `sync-agent-rules` hook\n"
        "entry matching pointstream's `.pre-commit-config.yaml`.",
        "There is no `.pre-commit-config.yaml` in this repo. Ablation CI now runs\n"
        "`tools/sync_agent_rules.py --check` so generated agent-rule files stay in\n"
        "sync with `AGENTS.md`. If pre-commit gets adopted later, add a matching\n"
        "`sync-agent-rules` hook entry.",
    )
    return text


def build_agents_md(source: str, *, framing: str, critical: str | None) -> str:
    text = GENERATED_BANNER.sub("", source)
    text = HOST_BLOCK.sub("\n", text)
    text = OLD_HOST_TAIL.sub("\n", text)
    text = SHARED_IMPORT.sub("\n\n", text)
    if OLD_FRAMING.search(text):
        text = OLD_FRAMING.sub(framing, text, count=1)
    else:
        # Insert framing after the first blank-line-separated intro block
        parts = text.split("\n\n", 1)
        if len(parts) == 2:
            text = parts[0] + "\n\n" + framing + parts[1]
        else:
            text = text.rstrip() + "\n\n" + framing
    text = soft_claudeisms(text).rstrip() + "\n"
    if critical and "<!-- copilot-critical:start -->" not in text:
        # Place critical block right after framing paragraph
        needle = framing.rstrip() + "\n"
        if needle in text:
            text = text.replace(needle, needle + "\n" + critical.strip() + "\n\n", 1)
        else:
            text = framing + critical.strip() + "\n\n" + text
    return text


def thin_claude(display: str, hooks_note: str) -> str:
    return (
        f"# {display} — Claude Code\n\n"
        "@AGENTS.md\n\n"
        "That import is the whole point of this file: `AGENTS.md` holds the project's\n"
        "real rule set, read directly by every other agent, and Claude Code is the only\n"
        "one that will not look at it on its own. Add nothing here that is not\n"
        "specific to Claude Code — if it applies to any other agent, it belongs in\n"
        "`AGENTS.md` (and if it applies to every project on this host, in\n"
        "`~/.agent-rules/AGENTS.md`).\n\n"
        "## Claude-specific notes\n\n"
        "- Host-wide rules reach this session twice: once from `~/.claude/CLAUDE.md`,\n"
        "  which Claude loads on its own, and once from the `host-rules` block inside\n"
        "  `AGENTS.md`. The block exists for cloud agents that never see this host's\n"
        "  home directory, so the duplication is deliberate, not drift.\n"
        f"{hooks_note}"
        "- Sessions spawned with `spawn_task` chips get their own worktree under\n"
        "  `.claude/worktrees/`. Sessions started any other way share this checkout's\n"
        "  HEAD — see the concurrency rules in `AGENTS.md` before running two at once.\n"
    )


def ensure_symlink(link: Path, target: str) -> None:
    if link.is_symlink() or link.exists():
        if link.is_symlink() and str(link.readlink()) == target:
            return
        if link.is_dir() and not link.is_symlink():
            shutil.rmtree(link)
        else:
            link.unlink()
    link.symlink_to(target)


def flip_skills_to_claude(repo: Path) -> None:
    """Prefer real skills under .claude/; .agents/skills -> symlink."""
    agents_skills = repo / ".agents" / "skills"
    claude_skills = repo / ".claude" / "skills"
    if claude_skills.is_symlink() and agents_skills.is_dir() and not agents_skills.is_symlink():
        claude_skills.unlink()
        agents_skills.rename(claude_skills)
        agents_skills.symlink_to("../.claude/skills")
        print(f"  flipped skills: .claude/skills real, .agents/skills -> symlink")
    elif agents_skills.is_symlink() and claude_skills.is_dir():
        print(f"  skills already Claude-canonical")
    elif claude_skills.is_dir() and not agents_skills.exists():
        agents_skills.parent.mkdir(parents=True, exist_ok=True)
        agents_skills.symlink_to("../.claude/skills")
        print(f"  linked .agents/skills -> .claude/skills")


def ensure_layout(repo: Path) -> None:
    claude = repo / ".claude"
    agents = repo / ".agents"
    cursor = repo / ".cursor"
    claude.mkdir(exist_ok=True)
    agents.mkdir(exist_ok=True)
    cursor.mkdir(exist_ok=True)

    flip_skills_to_claude(repo)

    # skills / agents: .agents -> .claude when .claude has the real tree
    for name in ("skills", "agents"):
        src = claude / name
        dst = agents / name
        if src.is_dir() and not src.is_symlink():
            ensure_symlink(dst, f"../.claude/{name}")
        elif dst.is_dir() and not dst.is_symlink() and not src.exists():
            # leave .agents real only if nothing under .claude yet
            pass

    workflows = agents / "workflows"
    workflows.mkdir(exist_ok=True)
    readme = workflows / "README.md"
    if not readme.exists():
        readme.write_text(WORKFLOWS_README)

    ensure_symlink(cursor / "commands", "../.agents/workflows")
    if (claude / "agents").is_dir():
        ensure_symlink(cursor / "agents", "../.claude/agents")
    (cursor / "rules").mkdir(exist_ok=True)


def ensure_gitignore(repo: Path) -> None:
    gi = repo / ".gitignore"
    text = gi.read_text() if gi.exists() else ""
    if ".agents/*" in text and "!.agents/workflows" in text:
        return
    if not text.endswith("\n"):
        text += "\n"
    gi.write_text(text + GITIGNORE_BLOCK)
    print("  updated .gitignore")


def vendor_sync(repo: Path) -> None:
    dst = repo / "tools" / "sync_agent_rules.py"
    dst.parent.mkdir(exist_ok=True)
    shutil.copy2(HOST_SYNC, dst)
    print(f"  vendored sync -> {dst}")


def run_sync(repo: Path) -> int:
    import subprocess

    return subprocess.call(
        [sys.executable, str(repo / "tools" / "sync_agent_rules.py")],
        cwd=repo,
    )


def migrate(
    repo: Path,
    *,
    display: str,
    framing: str,
    critical: str | None,
    guards: dict,
    hooks_note: str,
    force: bool,
) -> int:
    print(f"== {repo}")
    claude_md = repo / "CLAUDE.md"
    if not claude_md.is_file():
        print("  error: no CLAUDE.md", file=sys.stderr)
        return 1
    existing = claude_md.read_text()
    if "@AGENTS.md" in existing and not force:
        print("  already migrated (CLAUDE.md imports AGENTS.md); use --force to redo")
        # still vendor + sync + layout
        ensure_layout(repo)
        ensure_gitignore(repo)
        vendor_sync(repo)
        return run_sync(repo)

    # Prefer hand-edited CLAUDE when still SoT; else AGENTS without generated junk
    source = existing
    if "@AGENTS.md" in existing:
        source = (repo / "AGENTS.md").read_text()

    agents_body = build_agents_md(source, framing=framing, critical=critical)
    (repo / "AGENTS.md").write_text(agents_body)
    claude_md.write_text(thin_claude(display, hooks_note))
    (repo / ".agent-guards.json").write_text(
        json.dumps(guards, indent=2) + "\n"
    )
    print("  wrote AGENTS.md, CLAUDE.md, .agent-guards.json")

    ensure_layout(repo)
    ensure_gitignore(repo)
    vendor_sync(repo)

    # Drop obsolete Antigravity AGENTS copy under .agents/ if present
    extra = repo / ".agents" / "AGENTS.md"
    if extra.is_file():
        extra.unlink()
        print("  removed .agents/AGENTS.md")

    return run_sync(repo)


PRESETS: dict[str, dict] = {
    "presley": {
        "display": "PRESLEY",
        "framing": NEW_FRAMING_CI,
        "critical": """<!-- copilot-critical:start -->
If you read nothing else:

- **Never `rm` `results/`, `dataset/`, or `cache/`.** Invalidated runs get a
  specific `results/<hash>/` removed; wholesale deletion is unrecoverable and a
  hook blocks it.
- **Degradation experiments must use fixed-QP/CRF — never VBR.** A VBR
  degradation curve is not evidence; do not commission one.
- **A run with a non-empty `invariant_failures` is never citable.**
- **Never dress up imperceptible deltas** — run `presley-compare` before claiming
  a quality difference.
<!-- copilot-critical:end -->""",
        "guards": {
            "_comment": "Per-project values for the host-wide shell guards in ~/.agent-rules/scripts/. Read by every agent's hook adapter; see .agent-rules/README.md.",
            "protected": ["results", "dataset", "cache"],
            "detail": "experiment outputs / DAVIS symlinks / preprocessing cache",
            "entry_points": ["presley-run"],
        },
        "hooks_note": (
            "- Hooks for this project are wired in `.claude/settings.json`: repo state at\n"
            "  session start, the `rm` / wait-loop / long-run guards before every `Bash`\n"
            "  call, and a paper-sync reminder on stop. They call the shared scripts in\n"
            "  `~/.agent-rules/scripts/`; the values they enforce come from\n"
            "  `.agent-guards.json` in this repo.\n"
        ),
    },
    "moq3dgs": {
        "display": "MOQ3DGS",
        "framing": NEW_FRAMING_HAND,
        "critical": """<!-- copilot-critical:start -->
If you read nothing else:

- **Never `rm` `assets/` or `output/`.** A hook blocks wholesale deletion.
- **Real end-to-end tests must pass `--scene`/`--trace` explicitly** at
  `assets/bicycle.ply` and `assets/bicycle_trace.json` — do not use synthetic
  mock generators for transport validation.
- Keep MoQ transport (`src/moq3dgs/transport/`) decoupled from rendering
  (`src/moq3dgs/render/`).
<!-- copilot-critical:end -->""",
        "guards": {
            "_comment": "Per-project values for the host-wide shell guards in ~/.agent-rules/scripts/. Read by every agent's hook adapter; see .agent-rules/README.md.",
            "protected": ["assets", "output"],
            "detail": "3DGS PLY scenes / movement traces / weight symlinks / rendered frame + metrics outputs",
            "entry_points": [],
        },
        "hooks_note": (
            "- Hooks for this project are wired in `.claude/settings.json`: repo state at\n"
            "  session start and the `rm` guard before every `Bash` call. They call the\n"
            "  shared scripts in `~/.agent-rules/scripts/`; the values they enforce come\n"
            "  from `.agent-guards.json` in this repo.\n"
        ),
    },
    "TIGAS": {
        "display": "TIGAS",
        "framing": NEW_FRAMING_HAND,
        "critical": """<!-- copilot-critical:start -->
If you read nothing else:

- **Never wholesale-`rm` `outputs/`.** Per-run subdirectory deletion is fine; the
  tree costs real render+encode time and a hook blocks wiping it.
- The interactive browser/WebTransport/MoQ path and `docker/` are still
  scaffold-level — check `docs/REENTRY.md` before assuming they run.
- Prefer wrapper scripts under `scripts/` over hand-building `PYTHONPATH` CLIs.
<!-- copilot-critical:end -->""",
        "guards": {
            "_comment": "Per-project values for the host-wide shell guards in ~/.agent-rules/scripts/. Read by every agent's hook adapter; see .agent-rules/README.md.",
            "protected": ["outputs"],
            "detail": "Rendering/evaluation sweep outputs (frames, videos, tradeoff curves) - gitignored, costs real render+encode time to reproduce",
            "entry_points": [],
        },
        "hooks_note": (
            "- Hooks for this project are wired in `.claude/settings.json`: repo state at\n"
            "  session start and the `rm` guard before every `Bash` call. They call the\n"
            "  shared scripts in `~/.agent-rules/scripts/`; the values they enforce come\n"
            "  from `.agent-guards.json` in this repo.\n"
        ),
    },
    "4DGStudy": {
        "display": "4DGStudy",
        "framing": NEW_FRAMING_HAND,
        "critical": """<!-- copilot-critical:start -->
If you read nothing else:

- Always run inside the `fourdgstudy` conda env; manage deps via `pyproject.toml`.
- Heavy jobs must use `fourdgstudy.utils.gpu.select_gpu_device()` — do not hardcode
  a busy GPU 0.
- Encode evaluation clips with system FFmpeg at `/opt/local/bin/ffmpeg`
  (`libx265`, `veryfast`, `yuv420p`, CRF 23).
<!-- copilot-critical:end -->""",
        "guards": {
            "_comment": "Per-project values for the host-wide shell guards in ~/.agent-rules/scripts/. Read by every agent's hook adapter; see .agent-rules/README.md.",
            "protected": ["data"],
            "detail": "3DGS/4DGS scene dataset links under data/",
            "entry_points": [],
        },
        "hooks_note": (
            "- This project has no `.claude/settings.json` hooks yet. When hooks are\n"
            "  added, wire them to the shared scripts in `~/.agent-rules/scripts/` and\n"
            "  keep per-project values in `.agent-guards.json`.\n"
        ),
    },
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repo", type=Path, help="project root")
    parser.add_argument(
        "--preset",
        choices=sorted(PRESETS),
        help="named project preset (display, framing, guards, critical)",
    )
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    repo = args.repo.resolve()
    name = args.preset or repo.name
    if name not in PRESETS:
        print(f"error: no preset for {name}; pass --preset", file=sys.stderr)
        return 1
    cfg = PRESETS[name]
    return migrate(
        repo,
        display=cfg["display"],
        framing=cfg["framing"],
        critical=cfg["critical"],
        guards=cfg["guards"],
        hooks_note=cfg["hooks_note"],
        force=args.force,
    )


if __name__ == "__main__":
    raise SystemExit(main())
