#!/usr/bin/env python3
"""Deliver the host rules to Claude Code as a core plus deferred rule files.

`../AGENTS.md` stays **complete and hand-edited** — it is what Cursor,
Antigravity, Codex and Copilot read, none of which has a deferred-rule
mechanism, and splitting it would break them. What this script generates is
Claude Code's copy of the same bytes, in two pieces:

    ../generated/claude-host-core.md      always loaded (via ~/.claude/CLAUDE.md)
    ../generated/claude-host-rules/<slug>.md   loaded on demand, one per
                                          `<!-- scope: … -->` section

A generated rule file carries `paths:` frontmatter. Claude Code loads it with
`load_reason: path_glob_match` the moment the session touches a matching file,
so a rule about tests costs nothing until someone opens a test.

**The trigger is a path match and nothing else.** Verified against the CLI:
the only load reasons are `session_start`, `nested_traversal`,
`path_glob_match`, `include` and `compact` — there is no description-based
semantic trigger the way skills have. So a section is only worth scoping when
touching a file reliably precedes needing the rule. "Bound before believing"
fires when you *read a number*, which no glob can catch; marking it would
quietly stop delivering it. Two sections qualify today, and the honest saving
is ~35 lines, not the third of the file a line count suggests.

    python3 sync_host_rules.py            # write
    python3 sync_host_rules.py --check    # exit 1 if the outputs are stale

`--check` is the gate: run it after editing AGENTS.md. It also runs the
conservation check below.

**Conservation.** Every non-blank line of AGENTS.md must appear in the core or
in exactly one rule file, never both and never nowhere. A generator will
happily emit well-formed files that quietly dropped a paragraph, and a rule
nobody reads is worse than one nobody wrote — so this is checked directly
rather than smoke-tested.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

HOST_DIR = Path(__file__).resolve().parent.parent
AGENTS_MD = HOST_DIR / "AGENTS.md"
OUT_DIR = HOST_DIR / "generated"
CORE = OUT_DIR / "claude-host-core.md"
RULES_DIR = OUT_DIR / "claude-host-rules"
CLAUDE_RULES = Path.home() / ".claude" / "rules"

SCOPE_MARKER = re.compile(r"^<!--\s*scope:\s*(?P<globs>[^>]+?)\s*-->[ \t]*$", re.MULTILINE)
BANNER = "<!-- generated by .agent-rules/scripts/sync_host_rules.py — edit AGENTS.md -->"


class Scoped:
    def __init__(self, title: str, globs: list[str], body: str):
        self.title = title
        self.globs = globs
        self.body = body

    @property
    def slug(self) -> str:
        s = re.sub(r"[^a-z0-9]+", "-", self.title.lower()).strip("-")
        return f"host-{s}"[:60]


def split_scoped(text: str) -> tuple[str, list[Scoped]]:
    """Return (core, scoped sections), by `<!-- scope: -->` markers."""
    scoped: list[Scoped] = []
    core_parts: list[str] = []
    pos = 0
    for marker in SCOPE_MARKER.finditer(text):
        heading_start = text.index("\n", marker.end()) + 1
        if not text[heading_start:].startswith("## "):
            raise ValueError(
                f"scope marker at offset {marker.start()} is not immediately "
                "above a '## ' heading"
            )
        # The section runs to the next '## ' heading (or a following marker).
        rest = text[heading_start + 3 :]
        nxt = re.search(r"^(<!--\s*scope:|## )", rest, re.MULTILINE)
        end = heading_start + 3 + (nxt.start() if nxt else len(rest))
        title = text[heading_start + 3 : text.index("\n", heading_start)].strip()
        globs = [g.strip() for g in marker.group("globs").split(",") if g.strip()]
        if not globs:
            raise ValueError(f"scope marker above '{title}' lists no globs")
        scoped.append(Scoped(title, globs, text[heading_start:end].rstrip() + "\n"))
        core_parts.append(text[pos : marker.start()])
        pos = end
    core_parts.append(text[pos:])
    core = re.sub(r"\n{3,}", "\n\n", "".join(core_parts)).strip() + "\n"
    return core, scoped


def render_core(core: str, scoped: list[Scoped]) -> str:
    if not scoped:
        return f"{BANNER}\n\n{core}"
    index = "\n".join(
        f"- **{s.title}** — loads when you touch `{'`, `'.join(s.globs[:3])}`"
        + ("…" if len(s.globs) > 3 else "")
        for s in scoped
    )
    note = (
        f"{BANNER}\n\n"
        "<!-- Claude Code's copy of the host rules. AGENTS.md is the file to\n"
        "edit; it stays complete for the agents that read it whole. -->\n\n"
        f"{core}\n"
        "## Rules that load on demand\n\n"
        "These sections are not in your context right now. Claude Code loads\n"
        "each the moment this session touches a matching file. Read one\n"
        "directly from `.agent-rules/AGENTS.md` if you need it sooner.\n\n"
        f"{index}\n"
    )
    return note


def render_rule(item: Scoped) -> str:
    globs = ", ".join(item.globs)
    return (
        "---\n"
        f"paths: {globs}\n"
        f"description: Host rule — {item.title}\n"
        "---\n\n"
        f"{BANNER}\n\n"
        f"{item.body}"
    )


def plan() -> dict[Path, str]:
    text = AGENTS_MD.read_text(encoding="utf-8")
    core, scoped = split_scoped(text)
    out = {CORE: render_core(core, scoped)}
    for item in scoped:
        out[RULES_DIR / f"{item.slug}.md"] = render_rule(item)
    return out


def conservation_errors(planned: dict[Path, str]) -> list[str]:
    """Every AGENTS.md line must land in exactly one generated file."""
    source = [
        ln.strip()
        for ln in AGENTS_MD.read_text(encoding="utf-8").splitlines()
        if ln.strip() and not SCOPE_MARKER.match(ln)
    ]
    seen: Counter[str] = Counter()
    for body in planned.values():
        for ln in body.splitlines():
            if ln.strip():
                seen[ln.strip()] += 1
    errors = []
    for ln in source:
        if seen[ln] == 0:
            errors.append(f"LOST: {ln[:90]}")
        elif seen[ln] > 1 and source.count(ln) == 1:
            errors.append(f"DUPLICATED x{seen[ln]}: {ln[:80]}")
    return errors


def stale(planned: dict[Path, str]) -> list[Path]:
    out = [p for p, body in planned.items() if not p.is_file() or p.read_text() != body]
    if RULES_DIR.is_dir():
        out += [p for p in RULES_DIR.glob("*.md") if p not in planned]
    return out


def link_into_claude(planned: dict[Path, str]) -> list[str]:
    """Symlink the generated rules into ~/.claude/rules/, farm-style."""
    msgs = []
    CLAUDE_RULES.mkdir(parents=True, exist_ok=True)
    wanted = {p.name for p in planned if p.parent == RULES_DIR}
    for name in sorted(wanted):
        link, target = CLAUDE_RULES / name, RULES_DIR / name
        if link.is_symlink() and link.readlink() == target:
            continue
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(target)
        msgs.append(f"linked ~/.claude/rules/{name}")
    for link in CLAUDE_RULES.glob("host-*.md"):
        if link.name not in wanted and link.is_symlink():
            link.unlink()
            msgs.append(f"unlinked stale ~/.claude/rules/{link.name}")
    return msgs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if stale")
    args = ap.parse_args()

    try:
        planned = plan()
    except ValueError as exc:
        # A malformed `<!-- scope: -->` marker is an editing mistake in
        # AGENTS.md, not a crash. Say which one, and exit non-zero so a gate
        # catches it, without a traceback that buries the sentence that helps.
        print(f"AGENTS.md scope marker problem: {exc}", file=sys.stderr)
        return 1
    errors = conservation_errors(planned)
    if errors:
        print("Conservation check FAILED — AGENTS.md content would be lost:")
        for e in errors:
            print("  " + e)
        return 1

    outdated = stale(planned)
    if args.check:
        if outdated:
            print("Stale, run `python3 sync_host_rules.py`:")
            for p in outdated:
                print("  " + str(p))
            return 1
        print(f"up to date ({len(planned)} files, conservation OK)")
        return 0

    RULES_DIR.mkdir(parents=True, exist_ok=True)
    for p, body in planned.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body, encoding="utf-8")
    for p in RULES_DIR.glob("*.md"):
        if p not in planned:
            p.unlink()
            print("removed stale", p.name)
    for msg in link_into_claude(planned):
        print(msg)
    print(f"wrote {len(planned)} files, conservation OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
